### ISSUE TITLE
not able to logn to Nextcloud server

### ISSUE THREAD

**Issue by stephancordes** [alexcustos/linkasanote#1]
Hi,

 i am not able to login to my Nextcloud Server.
https://cloud.xxxxxx.xxxx  (without any port)
The connect-button stys gray.

Regards
Stephan

**Comment by alexcustos** [comment]
Hello Stephan,
Would you try to change screen orientation and check if the button stays gray? There is one weird bug, sometimes the Connection Status is not checked when focus leave the Server Address field. It would be great if you provide me more details about this issue.
