### ISSUE TITLE
Graveyard for notes

### ISSUE THREAD

**Issue by smaragdus** [alexcustos/linkasanote#4]
It is my fault that I started using [LaaNo](https://laano.net/) without proper testing and after adding 20 links with many notes to them I discovered that I cannot copy or edit the notes, only the links as edit mode works only for links. Also there is no way to export a link with its notes to common useful formats such as TXT or HTML and as a result I cannot use these notes on my desktop. Yes OwnCloud synchronization worked but I got useless for me JSON files with arbitrary names. So there is no way to manually copy data from [LaaNo](https://github.com/alexcustos/linkasanote) to [Simplenote](https://app.simplenote.com/). Initially I could not believe that there was no way to copy the contents of a note and I was convinced that I was missing something. So now I have two choices, either uninstall LaaNo and lose all my work or keep it until I manually type down all the notes I created from LaaNo to Simplenote.

In my opinion LaaNo is badly designed. If it is not abandoned you might add at least two new features:

- Export (to TXT or HTML files, title - link - notes);
- Edit notes (copy notes contents, edit notes- cut/copy/paste/delete, delete notes individually, not the link but the notes added to it);

If I am missing something please correct me. Is there a way to copy text from individual notes?

**Comment by alexcustos** [comment]
Hello @smaragdus, thank you for using the app. It's not abandoned, I just decided to migrate the project to Kotlin before introducing new features, but it turned out to be quite time-consuming. I hope I'll finish it soon.

For the question, you are correct it's a bit challenging to reassemble data from JSON, but the app exports the original `SQLite` database as a backup, so you can use a DB browser to query and save data to a more useful format.

**Comment by smaragdus** [comment]
@alexcustos 

Thank you for your quick response, I hope I did not sound harsh and rude, it is just that LaaNo is not very suitable for my use.

I can imagine how much time and effort you have spent on it and I am glad that LaaNo is not abandoned.

I still think that options for copying/editing/exporting links+notes to separate files would be very handy and useful. I do not know how much work it would require to implement export to text or HTML.

Thank you for the tip for using a database browser to extract and export data.

Since you answered my question how to extract and transfer data I will close this issue, If needed, I can open new separate issues for note editing and data export.

Regards
